name: ALOT
main: fr.paulem.alot.ALOT
version: 1.0
load: STARTUP
author: Paulem
website: https://linktr.ee/paulem
description: A Lot Of Things
#1.17.1-1.20+
api-version: 1.17
commands:
  alot:
    description: ALOT's commands
    usage: /alot [reload/rl]
    permission: alot.admin
    aliases:
      - alotofthings